CREATE TABLE TOKEN
(
    ID                 BIGINT(20) NOT NULL AUTO_INCREMENT COMMENT '유저 아이디',
    ACCESS_TOKEN       VARCHAR(512) NOT NULL UNIQUE,
    REFRESH_TOKEN      VARCHAR(512) NOT NULL UNIQUE,
    USER_ID            BIGINT       NOT NULL,
    ACCESS_EXPIRES_AT  DATETIME     NOT NULL,
    REFRESH_EXPIRES_AT DATETIME     NOT NULL,
    CREATED_AT         DATETIME DEFAULT CURRENT_TIMESTAMP,
    REVOKED            BOOLEAN  DEFAULT FALSE,
    PRIMARY KEY (ID),
    CONSTRAINT FK_USER_ID FOREIGN KEY (USER_ID) REFERENCES USER (ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;